spring:
  redis:
    jedis:
      pool:
        max-wait: 5000
        max-idle: 50
        max-active: 5
    cluster:
      nodes: 10.1.84.22:10001,10.1.84.22:10002,10.1.84.22:10003,10.1.84.22:10004,10.1.84.22:10005,10.1.84.22:10006
    timeout: 500
  kafka:
    bootstrap-servers: 10.1.84.22:9092,10.1.84.22:9093,10.1.84.22:9094
    consumer:
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://106.14.13.61:3306/glodonseckill?useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
mybatis:
  type-aliases-package: com.glodon.seckillcommon.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9188