spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://106.14.13.61:3306/glodonseckill?useSSL=false&allowMultiQueries=true
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
mybatis:
  type-aliases-package: com.glodon.seckilladmin.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8090